
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Example configuration.yaml entry
discovery:
#  ignore:
#    - yeelight
yeelight:
  devices:
    192.168.0.34:
      name: Pasillo

sensor:
  - platform: mqtt
    name: "Temperature"
    state_topic: "v1/devices/me/telemetry"
    unit_of_measurement: '°C'
    value_template: "{{ value_json.temperature }}"
  - platform: mqtt
    name: "Humidity"
    state_topic: "v1/devices/me/telemetry"
    unit_of_measurement: '%'
    value_template: "{{ value_json.humidity }}"
